// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package nav

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Nav() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<nav id=\"nav\" class=\"bg-gray-800\"><div id=\"container\" class=\"mx-auto max-w-7xl px-2 sm:px-6 lg:px-8\"><div class=\"flex h-20 items-center gap-4\"><img class=\"h-16 w-auto\" src=\"https://img.icons8.com/?size=100&amp;id=114426&amp;format=png&amp;color=000000\" alt=\"todo icon\"><div class=\"flex-grow flex justify-center items-center gap-4\"><a href=\"/\" class=\"rounded-md px-3 py-2 text-3xl font-medium text-gray-300 hover:bg-gray-700 hover:text-white\">Home</a> <a href=\"/about\" class=\"rounded-md px-3 py-2 text-3xl font-medium text-gray-300 hover:bg-gray-700 hover:text-white\">About</a></div></div></div></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
