---
# https://taskfile.dev
version: "3"

tasks:
  assets:
    desc: Build the assets
    cmds:
      - npx tailwindcss -i ./internal/assets/tailwind.css -o ./internal/assets/dist/styles.css
  generate:
    desc: Generate stuff and things
    cmds:
      - go generate ./...
  run:
    desc: Run the application
    deps:
      - assets
      - generate
    cmds:
      - go run ./cmd/server/...
