---
# https://taskfile.dev
version: "3"

tasks:
  assets:
    desc: Build the assets
    cmds:
      - npx tailwindcss -i ./assets/css/input.css -o ./assets/css/output.css
  generate:
    desc: Generate stuff and things
    cmds:
      - go generate ./...
  run:
    desc: Run the application
    deps:
      - assets
      - generate
    cmds:
      - go run ./cmd/server/...
