// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package table

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/anucha-tk/go_todo/internal/domain"
	"github.com/anucha-tk/go_todo/internal/templates/partials"
	"github.com/anucha-tk/go_todo/internal/templates/partials/tbody"
)

func Table(todos []*domain.Todo) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<section id=\"todos\" class=\"flex flex-col item-center mx-auto w-fit\"><div id=\"processing\" class=\"htmx-indicator\">Processing...</div><div class=\"flex flex-col\"><div><div class=\"inline-block min-w-full py-2 sm:px-6 lg:px-8\"><div class=\"overflow-hidden\"><div class=\"flex justify-end\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = partials.AddTodoForm().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><table class=\"min-w-full text-left text-sm font-light\" id=\"todo_table\"><thead class=\"border-b font-medium dark:border-neutral-500 text-gray-800\"><tr><th scope=\"col\" class=\"px-6 py-4\">#</th><th scope=\"col\" class=\"px-6 py-4\">Description</th><th scope=\"col\" class=\"px-6 py-4\">Completed</th><th scope=\"col\" class=\"px-6 py-4\">CreatedAt</th><th scope=\"col\" class=\"px-6 py-4\">UpdatedAt</th><th scope=\"col\" class=\"px-6 py-4\">Actions</th></tr></thead>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = tbody.TableBody(todos).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</table></div></div></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
